version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "4200:80"
    volumes:
      - ./apps/backoffice:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./
      dockerfile: docker/backend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/api-backoffice:/src
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: mydb

  db:
    image: mysql:8
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data:
