/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateClientDto {

  /**
   * email
   */
  email: string;

  /**
   * Nombre del cliente
   */
  name: string;

  /**
   * telefono
   */
  phone: string;
}
