/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateUserDto {

  /**
   * Correo electrónico
   */
  email: string;

  /**
   * Contraseña
   */
  password: string;

  /**
   * Nombre de usuario
   */
  username: string;
}
