/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateSettingDto {

  /**
   * Clave de configuración
   */
  key: string;

  /**
   * Valor de la configuración
   */
  value: string;
}
